# Generated by Django 6.0.1 on 2026-02-04 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_customuser_display_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='display_name',
            field=models.CharField(blank=True, help_text='Custom display name (optional)', max_length=100, null=True),
        ),
    ]
